### ISSUE TITLE
requirements.txt incompleto

### ISSUE THREAD

**Issue by hector-garrido** [hector-garrido/niunamuertevial#9]
@categulario ayer se probó el approach sin conda.
Al final fue exitoso, pero en el camino se tuvo que instalar openpyxl tras requirements.txt
¿Probaste requirements.txt en tu equipo? Si no fue el caso, lo mejor será añadir openpyxl a requirements.txt de manera unánime.

**Comment by categulario** [comment]
Podemos añadir `openpyxl` a `requirements.txt`, sin embargo considero que una opción mejor es no usarlo en absoluto, por la única razón de que realmente no es necesario. Menos dependencias hacen un entorno más fácil de reproducir y el uso de openpyxl es solamente para abrir un archivo de excel del que solo se considera la primera hoja y la primera columna. Podemos reemplazar esto por un archivo de texto plano o un archivo csv que se puede leer con la biblioteca estándar. ¿cómo ves?

**Comment by hector-garrido** [comment]
Creo que es mejor añadir openpyxl.

Por un lado, la prioridad es facilitar la tarea de recolección de info, y requerir un csv como input puede llevar a problemas de encoding desde el inicio con los distintos caracteres que ocupan las urls, lo cual me pasó durante el desarrollo.

Por otro lado, si bien omitir openpyxl lo hace más ligero, actualmente el entorno no es pesado, y en todo caso su uso no va a escalar en ningún sentido.
